CREATE CAST (VARCHAR AS user_role) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS employee_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS attendance_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS leave_request_status) WITH INOUT AS IMPLICIT;
